### ISSUE TITLE
Добавить в раздел Тестирования информацию о Тестере

### ISSUE THREAD

**Issue by JohnyDeath** [Oxotka/StackTechnologies1C#6]
Есть замечательный продукт для автоматизированного тестирования - [Тестер](http://tester.help/).
Для разработчика, который сам пишет тесты, этот продукт будет очень полезным и удобным.
Также есть свой CI-Allure, т.е. развертывание и понимание будет максимально быстрым, потому что остаешься фактически в той же среде 1С

**Comment by Oxotka** [comment]
Да, забыл о нем. Добавлю в ближайшее время. Спасибо!

**Comment by Oxotka** [comment]
Добавил про тестер
